name: dating_app
description: "A Dating App."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  equatable: ^2.0.7
  # firebase implementation
  firebase_core: ^3.1.1
  firebase_crashlytics: ^4.0.2
  firebase_analytics: ^11.2.0
  flutter_bloc: ^9.1.1
  get_it: ^8.0.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  image_picker: ^1.0.7
  intl: ^0.19.0
  loggy: ^2.0.3
  lottie: ^3.3.1
  json_annotation: ^4.9.0
  shared_preferences: ^2.5.3


dev_dependencies:

  flutter_test:
    sdk: flutter

  build_runner: ^2.5.4
  flutter_lints: ^5.0.0
  json_serializable: ^6.9.5
  intl_utils: ^2.8.11

flutter_intl:
  enabled: true
  main_locale: tr
  arb_dir: lib/core/l10n
  output_dir: lib/core/generated

flutter:
  generate: true
  uses-material-design: true

  fonts:
    - family: EuclidCircularA
      fonts:
        - asset: assets/fonts/EuclidCircularA-Regular.ttf
        - asset: assets/fonts/EuclidCircularA-Medium.ttf
          weight: 500
        - asset: assets/fonts/EuclidCircularA-Bold.ttf
          weight: 700

  assets:
    - assets/images/
    - assets/icons/
    - assets/lottie/
